version: '3.2'

services:
  db:
    image: postgis/postgis:15-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qb

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: $DOCKER_IMAGE_BACKEND
    environment:
      CI: "true"
      # https://github.com/pytest-dev/pytest/issues/7443
      PYTEST_ADDOPTS: "--color=yes"
      APP_ENVIRONMENT: test
      APP_TYPE: web
      DJANGO_SECRET_KEY: "XXXXXXXXXXXXXXXXXXXXXXXXXX"
      # To overwrite this values. set the values in .env
      DJANGO_DEBUG: "true"
      APP_DOMAIN: localhost:8311
      APP_HTTP_PROTOCOL: http
      APP_FRONTEND_HOST: localhost:3111
      SESSION_COOKIE_DOMAIN: localhost
      CSRF_COOKIE_DOMAIN: localhost
      DJANGO_ALLOWED_HOST: '*'
      # Database
      DJANGO_DB_NAME: qb
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: postgres
      DJANGO_DB_PORT: 5432
      DJANGO_DB_HOST: db
      DJANGO_CORS_ORIGIN_REGEX_WHITELIST: localhost
      # Redis
      CELERY_REDIS_URL: redis://redis:6379/1
      DJANGO_CACHE_REDIS_URL: redis://redis:6379/2
      TEST_DJANGO_CACHE_REDIS_URL: redis://redis:6379/12
      # EMAIL
      EMAIL_FROM: dev@example.com
      # Enketo
      ENKETO_DOMAIN: http://localhost:8005
    volumes:
      - ./coverage/:/code/coverage/
      - ./ci-share/:/ci-share/
    depends_on:
      - db
      - redis
