# Generated by Django 4.2.5 on 2023-11-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='alumni',
            field=models.BooleanField(default=False),
        ),
    ]
